### ISSUE TITLE
How to use .setRequestInterception()

### ISSUE THREAD

**Issue by per4uk93** [And93/protractor-puppeteer-plugin#17]
Hi! Please add, if you have, some examples, how to use .setRequestInterception() with protractor tests through your plugin?) Thx

**Comment by And93** [comment]
Hi!
Thanks for the question.

But there is nothing special. Just notice in particular that `browser.cdp` has the following properties: 
- target: https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#class-target
- client: https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#class-cdpsession
- page: https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#class-page
- browser: https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#class-browser

And `browser.puppeteer` has the following:
- https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#class-puppeteer

Now you can use everything that these classes have.

Example:
```
const {browser} = require('protractor');

describe('Protractor + Puppeteer.', () => {
    it('Mocking response', async () => {

        await browser.cdp.page.setRequestInterception(true);

        browser.cdp.page.on('request', async request => {
            if (request.url().includes('photos')) {
                await request.respond({
                    body: '[{title: "Hello World!!!"}]'
                })
            } else {
                await request.continue();
            }
        });

        await browser.cdp.page.goto('http://jsonplaceholder.typicode.com/photos');
        // or
        // await browser.waitForAngularEnabled(false);
        // await browser.get('http://jsonplaceholder.typicode.com/photos');
    });
});
```

**Comment by per4uk93** [comment]
Thank you!)
